---

##########################################################
# Check to see if PAD process is running
##########################################################
- name: Check status of PAD process
  shell: "ps -ef|grep nco_pad|grep -v grep|cut -d' ' -f24|cut -d'/' -f10"
  become_user: netcool
  become: yes
  become_method: enable
  register: pad_status

- name: Debug PAD Status
  debug: var=pad_status.stdout
##########################################################


##########################################################
# Stop PAD and all processes using startup script
##########################################################
- name: Stop PAD
  shell: "source /home/netcool/.bashrc && /etc/init.d/nco stop"
  become: yes
  become_user: netcool
  environment:
      OMNIHOME: /opt/IBM/tivoli/netcool/omnibus
      NCHOME: /opt/IBM/tivoli/netcool
  register: stop_pad

- name: Debug Stopping PAD
  debug: var=stop_pad.stdout
##########################################################


##########################################################
# Uninstall Objectserver
##########################################################
- name: Uninstall IBM Omnibus ObjectServer
  shell: "/home/netcool/IBM/eclipse/tools/imcl -input /opt/segra_files/omnibus_uninstall_response_file.xml"
  become: true
##########################################################

##########################################################
# Uninstall Installation Manager         
##########################################################
- name: Uninstall IBM Install Manager
  shell: "/root/var/ibm/InstallationManager/uninstall/uninstall --launcher.ini /root/var/ibm/InstallationManager/uninstall/silent-uninstall.ini"
  become: true
##########################################################

- name: Uninstall yum packages using a list
  become: True
  yum:
    state: removed
    name:
      - tar
      - hostname
      - unzip
      - audit-libs
      - fontconfig
      - freetype
      - compat-libstdc++-33.i686
      - glibc.i686
      - gtk2
      - libICE
      - libSM
      - libX11
      - libXau
      - libXcursor
      - libXext
      - libXft
      - libXmu
      - libXp
      - libXpm
      - libXrender
      - libXt
      - libXtst
      - libstdc++.i686
      - libgcc.i686
      - libjpeg-turbo
      - libpng12
      - motif
      - dejavu-fonts-common
      - dejavu-sans-fonts
      - expat
      - glibc
      - libgcc      
      - libidn
      - libstdc++
      - libuuid
      - libxcb
      - nss-softokn-freebl
      - pam
      - zlib
      - nss-softokn-freebl.i686
      - compat-libstdc++-33
      - git
      - logrotate
      - strace
      - vim
      - bc
      - pam.i686
      - xorg-x11-xauth.x86_64
      - xorg-x11-apps-7.7-7.el7.x86_64
      - xterm
##########################################################



##########################################################
# Remove Directories
##########################################################
- name: Remove /opt/IBM Directory 
  file:
    path: /opt/IBM
    state: absent 
    owner: netcool
    group: ncoadmin
    mode: 0775
    recurse: yes

- name: Remove /opt/accuoss/repository Directory 
  file:
    path: /opt/accuoss/repository
    state: absent 
    owner: netcool
    group: ncoadmin
    mode: 0775
    recurse: yes

#- name: Remove /opt/accuoss/omnibus/scripts Directory 
#  file:
#    path: /opt/accuoss/omnibus/scripts
#    state: absent 
#    owner: netcool
#    group: ncoadmin
#    mode: 0775

- name: Remove /opt/accuoss/omnibus Directory 
  file:
    path: /opt/accuoss/omnibus
    state: absent
    owner: netcool  
    group: ncoadmin
    mode: 0775
    recurse: yes

#- name: Remove /opt/accuoss/omnibus/configs/objectserver Directory 
#  file:
#    path: /opt/accuoss/omnibus/configs/objectserver
#    state: absent
#    owner: netcool
#    group: ncoadmin
#    mode: 0775

#- name: create host config directory for objectserver
#  file:
#    path: /opt/accuoss/omnibus/logs/objectserver
#    state: absent
#    owner: netcool
#    group: ncoadmin
#    mode: 0775

#- name: create InstallManager directory for objectserver
#  file:
#    path: /home/netcool/InstallationManager
#    state: absent
#    owner: netcool
#    group: ncoadmin
#    mode: 0775

- name: Remove /home/netcool/repository/core Directory 
  file:
    path: /home/netcool/repository/core 
    state: absent
    owner: netcool
    group: ncoadmin
    mode: 0775
    recurse: yes

########################################################
# Set permissions on files for netcool
########################################################
#- name: Set permissions for netcool on omnibus files
#  shell: "setfacl -m u:netcool:rwX /etc/shadow && setfacl -m u:netcool:rwX /etc/init.d/nco && setfacl -m u:netcool:r /etc/passwd && setfacl -m u:netcool:r /etc/group"
#  become: true
########################################################

########################################################
# Stop PAD and all processes using startup script
########################################################
#- name: Stop the probe using nco stop / nco start
#  service:
#    name: nco
#    state: stopped
########################################################

########################################################
# Remove omnibus admin accounts
########################################################
- user:
    name: netcool
    comment: "Omnibus admin account"
    uid: 10001
    shell: /bin/bash
    home: /home/netcool
    group: ncoadmin
    state: absent
    remove: yes
    password: "$6$ulGOJh6254sgt8QS$C/XftgH.MkMor2X.GbZLIlsfSHKRkHjqAANtiV0zlARH2R7m2.Kis.DICdm.45A7ntp0ImCndPutANY68.PSA/"
  become: true

- group:
    name: ncoadmin
    gid: 5500
    state: absent
  become: true
######################################################
