---
- hosts: 10.160.100.119 
  strategy: debug
  gather_facts: no
  #become: yes
  vars_files:
    #- "ansible-omnibus-objectserver-agg-base-install.yml"
   # - "env.yml"
  roles:
#    - role: base
#      tags: base

    - role: ansible-omnibus-objectserver-agg-base-install 
      tags: ansible-omnibus-objectserver-agg-base-install 
